### ISSUE TITLE
Add docker file

### ISSUE THREAD

**Issue by Guseyn** [Guseyn/nodes.js#4]

**Comment by Itz-Agasta** [comment]
Hi, @Guseyn  I've created a PR (#5) to add Docker support for local development and testing. Please take a look and let me know if there are any adjustments you'd like.
Also, I have seen the `README.md` file is not very informative. Would you like me to update the README and also add the Docker usage instructions?

Thanks!

**Comment by Guseyn** [comment]
@Itz-Agasta thank you. It's WIP. I am planning to release it today. I am working on Readme at the moment. I will come back to your PR once I finish with my work.

**Comment by Guseyn** [comment]
@Itz-Agasta, you can check now Readme for more information.

**Comment by Itz-Agasta** [comment]
@Guseyn  The documentation is indeed well-detailed and helpful! I suggest adding a Table of Contents to enhance navigation, following the universal README format. Additionally, a section on How to Create and Run the Docker Image would be valuable for new users.

Also, please feel free to check my PR ( #5 ), where I’ve included steps for setting up the Docker image and container. If you have some time, I'd appreciate your review on it as well! And congratulations on your new release.  🎉
